# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main

pool:
  vmimage: "ubuntu-latest"

variables:

 isappd1: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'appd1/') ]
 isappd2: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'appd2/') ]
 isappd3: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'appd3/') ]
 isappd4: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'appd4/') ]
 isappd5: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'appd5/') ]
# isplatform: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'platform') ]
stages:
- stage: CHECK_TRIGGER
  jobs:
  - job: checktrigger
    steps:
      - script: |
          
          echo  is triggered by appd1 branch  ? $(isappd1) 
          echo  is triggered by appd2 branch  ? $(isappd2) 
          echo  is triggered by appd3 branch  ? $(isappd3) 
          echo  is triggered by appd4 branch  ? $(isappd4) 
          echo  is triggered by appd5 branch  ? $(isappd5) 

- stage: build
      
  jobs:
    - job: build
      variables:
       - name: tda-ui-redirect
         value: "https://tdatempdevstatichosting.z7.web.core.windows.net"
      steps:
        - script: |
            prsource=$(System.PullRequest.SourceBranch)
            echo prsource is $prsource
            slot_name=$(echo $prsource | cut -d "/" -f1 | cut -c 4-)
            echo slotname is $slot_name
            if [[ ( $slot_name == "d1" ) ]]
            then
            echo "##vso[task.setvariable variable=tda-ui-redirect]https://tdatempdevstatichosting.z7.web.core.windows.net/$slot_name"
            echo "##vso[task.setvariable variable=public_url]https://tdatempdevstatichosting.z7.web.core.windows.net/$slot_name"
            echo "##vso[task.setvariable variable=slot_name]$slot_name"
            elif [[ ( $slot_name == "d2" ) ]]
            then
            echo "##vso[task.setvariable variable=tda-ui-redirect]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=public_url]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=slot_name]'$slot_name'"
            elif [[ ( $slot_name == "d3" ) ]]
            then
            echo "##vso[task.setvariable variable=tda-ui-redirect]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=public_url]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=slot_name]'$slot_name'"
            echo "##vso[task.setvariable variable=slot_name]'$slot_name'"
            elif [[ ( $slot_name == "d4" ) ]]
            then
            echo "##vso[task.setvariable variable=tda-ui-redirect]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=public_url]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=slot_name]'$slot_name'"
            elif [[ ( $slot_name == "d5" ) ]]
            then
            echo "##vso[task.setvariable variable=tda-ui-redirect]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=public_url]https://tdatempdevstatichosting.z7.web.core.windows.net/'$slot_name'"
            echo "##vso[task.setvariable variable=slot_name]'$slot_name'"
            else
            echo its not matching with slot
            fi
             
          displayName: set var
            
        - script: 
              set -x
              echo url is "$(tda-ui-redirect)"

              echo slotname is "$(slot_name)"

              echo public url is "$(public_url)"

          displayName: get var
              


