pr:
- main

pool:
  vmimage: "ubuntu-latest"

stages:
  
- stage: DEPLOY_TO_APPD2
  condition: eq(variables.isappd1, 'true')
  jobs:
    - template: deploy.yml
      parameters:
        storageaccount: 'tdatempdevstatichosting'
        sub: 'arup-it-dev'
        rg: 'arup-tda-dev-rg'
        env: 'dev'
        fld: '$web/d1'
        dir: 'd1/*'
  
