pr:
- main

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches: 
  include:
    - main
   

variables:

 isappd1: $[ startsWith(variables['System.PullRequest.SourceBranch'], 'appd1/') ]
 
pool:
  vmimage: "ubuntu-latest"

stages:
  
- stage: build
  
  jobs:
    - job: build
      steps:
        - script: |
            echo "its working on build"

- stage: deploy
  condition: ne(variables['Build.Reason'], 'PullRequest')
  jobs:
    - job: deploy
      steps:
        - script: |
            echo "$(Build.Reason)

