on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo " source is ${{ github.head_ref }}"
       echo " dest repo is ${{ github.base_ref }}"
       echo $GITHUB_REF
       echo $GITHUB_HEAD_REF
       prsource=GITHUB_REF
       echo $prsource
       printenv
      shell: bash
    - name: Az Pipelines Action
      uses: ladvivek7/Az_Pipeline@v1
      with:
        azure-devops-project-url: https://dev.azure.com/meganadhan/Megatest
        azure-pipeline-name: 'okta-test'
        azure-devops-token: h5kqd4jcdbkneyhejwagocjb7k7cs7xncutuluj5q3clmavgrj7a
        azure-pipeline-variables:  '{"pr_source": "$prsource", "variable2": "$GITHUB_REF"}'
       
        
