on:
    pull_request_review:
     types: [submitted]
jobs:
  build:
    if: ${{ startsWith( github.event.pull_request.head.ref, 'test') && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        
         echo " source is ${{ github.event.pull_request.head.ref }}"
         echo " dest repo is ${{ github.event.pull_request.base.ref }}"
        
         printenv
         
    - name: Az Pipelines Action
      uses: ladvivek7/Az_Pipeline@v1
      with:
          azure-devops-project-url: 'https://dev.azure.com/ovearup/Total%20Design%20Automation'
          azure-pipeline-name: 'TDA-apps-UAT-on-PR'
          azure-devops-token: '2kasuzjoo2ce57axvezh5i2phqgywtz3oleg6rl2jfsmgoo3gniq'
          azure-pipeline-variables:  '{"Is_app": "true", "System.PullRequest.SourceBranch": "${{ github.event.pull_request.head.ref }}"}'
       
        
