on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: alexrster/pipelines@v2
      with:
        azure-devops-project-url: https://dev.azure.com/meganadhan/Megatest
        azure-pipeline-name: 'okta-test'
        azure-devops-token: aadelkrftqj2lspvczrrswitk4voek67goyl27qx6titoswzc4ua
        azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}'
